language: php

php:
  - 5.3

before_script:
  - composer install --dev --no-interaction

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c build/phpunit.xml

after_script:
  - vendor/bin/coveralls -v